package Herramienta;

public class Interfaz extends javax.swing.JFrame {

    JCanvas jcanvas;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setVisible(true);
        setTitle("Herramienta Mockup");
        setLocation(360,150);
        jcanvas = new JCanvas(jPanel1.getSize());
        jPanel1.add(jcanvas);
        repaint();
    }

/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_cuadrado = new javax.swing.JButton();
        btn_circulo = new javax.swing.JButton();
        btn_triangulo = new javax.swing.JButton();
 	jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
	jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        jToolBar1.setOrientation(1);
        jToolBar1.setRollover(true);

        btn_cuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuenteImagenes/contenedor.png"))); // NOI18N
        btn_cuadrado.setFocusable(false);
        btn_cuadrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cuadrado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuadradoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_cuadrado);

        btn_circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuenteImagenes/texto.png"))); // NOI18N
        btn_circulo.setFocusable(false);
        btn_circulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_circulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_circuloActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_circulo);

        btn_triangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuenteImagenes/boton.png"))); // NOI18N
        btn_triangulo.setFocusable(false);
        btn_triangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_triangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trianguloActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_triangulo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jToolBar1, gridBagConstraints);
	
	jMenu1.setText("Accion");

        jMenuItem1.setText("Generar Caso de Uso");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);	

        pack();
    }// </editor-fold>                        

    private void btn_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {                                             
          jcanvas.selectFigura("Cuadrado");
    }                                            

    private void btn_circuloActionPerformed(java.awt.event.ActionEvent evt) {                                            
         jcanvas.selectFigura("Texto");
    }                                           

    private void btn_trianguloActionPerformed(java.awt.event.ActionEvent evt) {                                              
        jcanvas.selectFigura("Cuadrado");
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
      private javax.swing.JButton btn_circulo;
    private javax.swing.JButton btn_cuadrado;
    private javax.swing.JButton btn_triangulo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration                   
}
